name: Node.js app deploy to EKS private cluster

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is the latest stable
      id: install

    - name: Login to Amazon ECR, Build, tag, and push Docker image to Amazon ECR
      id: login-ecr
      run: |
        # Use IAM role attached to the EC2 instance for authentication
        $(aws ecr get-login --no-include-email --region ap-south-1 --registry-ids 737185589565)

        sudo docker build -t testpoc .
        sudo docker tag testpoc:latest 737185589565.dkr.ecr.ap-south-1.amazonaws.com/testpoc:latest
        sudo docker push 737185589565.dkr.ecr.ap-south-1.amazonaws.com/testpoc:latest

    - name: Update kube config
      run: aws eks update-kubeconfig --name Testpoc
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml
